[Settings]
ID = "fbec0c74-d903-4554-a677-f72a05d96160"

# Settings in the [build] context are global and are applied to all contexts unless otherwise overridden by more specific contexts.  

[build]
  # This is the directory to change to before starting a build.
  base    = "instagram/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "instagram/build/"
  # This will be your default build command
  command = "yarn build"